version: '2'

services:
    ontology:
        build:  ontology-mapping-chatbot/
        container_name: ontology
        privileged: true
        ports:
        - "8090:8000"
        volumes:
        - ./data_dumps:/ontology-mapping-chatbot/data_dumps
